#
# Python Dockerfile for Windows Docker Servers
#

# Pull base docker image
FROM python:3-windowsservercore

COPY . C:\data
WORKDIR C:\\data

RUN pip install -r requirements.txt

CMD ["py", "c:/data/sample/hello.py"]
